### ISSUE TITLE
[Bullet chart]: Cannot read properties of undefined (reading 'Series/Column/ColumnSeries.js') in react

### ISSUE THREAD

**Issue by niralivasoya** [highcharts/highcharts-angular#368] opened 2023-10-04 21:52 UTC
### Setup used
 - Reactjs
 
### Full code

```
import { simulation1 } from '@/data/ChartData';
import Highcharts from 'highcharts';
import bulletChart from 'highcharts/modules/bullet';
import HighchartsReact from 'highcharts-react-official';

bulletChart(Highcharts);

const HorizontalBarChartCarbon = () => {
    const defaultCarbonCutoffs = [100, 30, 40];

    const chartOptions = {
        chart: {
            type: 'bullet',
            height: 190,
            inverted: true,
        },
        title: {
            text: 'Carbon Output (kgCO2/m2/yr)',
            margin: 20,
            style: {
                fontSize: '14px',
                color: '#5D5C56',
                fontWeight: 600,
            },
            align: 'left',
        },
        xAxis: {
            categories: ['Operational CO2', 'Embodied CO2', 'Life Cycle CO2'],
            labels: {
                distance: 10,
                style: {
                    color: '#7C7A73',
                    fontSize: '11px',
                },
            },
            gridLineWidth: 1,
        },
        yAxis: {
            title: {
                text: null,
            },
            opposite: true,
            labels: {
                distance: 10,
                style: {
                    color: '#7C7A73',
                    fontSize: '11px',
                },
            },
            gridLineWidth: 1,
        },
        legend: {
            enabled: false,
        },
        plotOptions: {
            bullet: {
                color: '#794F9F',
                pointPadding: 0,
                pointWidth: 26,
            },
            targetOptions: {
                height: 1,
            },
        },
        series: [
            {
                name: 'Value',
                data: [
                    {
                        y: simulation1.EUI,
                        target: defaultCarbonCutoffs[0],
                    },
                    {
                        y: simulation1.CEDI,
                        target: defaultCarbonCutoffs[1],
                    },
                    {
                        y: simulation1.TEDI,
                        target: defaultCarbonCutoffs[2],
                    },
                ],
            },
        ],
    };

    return (
        <div>
            <HighchartsReact highcharts={Highcharts} options={chartOptions} />
        </div>
    );
};

export default HorizontalBarChartCarbon;
```

### Result

<img width="462" alt="image" src="https://github.com/highcharts/highcharts-angular/assets/32123446/7d4f1f85-6e78-4e04-853e-cf52c5f88a7e">

What is wrong here, I am getting the above error. It is working properly but in the console, I am getting this error continuously. 

I have used `Bullet`, especially for setting the marker (Targets). Please suggest if there is any alternate way to do this.

Thanks

**Comment by karolkolodziej** [comment] 2023-10-05 06:53
Hi @niralivasoya!
First of all, I'm not sure how this is connected to Angular 😅 

Nevertheless, I've tried to recreate this example but cannot get this error. 
Please explain or edit [the demo](https://stackblitz.com/edit/react-fs8npk?file=index.js) with the code that gives this error.

**Comment by karolkolodziej** [comment] 2023-10-05 10:26
Closing as a duplicate of: https://github.com/highcharts/highcharts-react/issues/434

**Closed by karolkolodziej** 2023-10-05 10:26 UTC

**Comment by niralivasoya** [comment] 2023-10-05 14:18
Thank you for your reply @karolkolodziej.
