### ISSUE TITLE
Bar High Chart with different positive and negative scale interval values

### ISSUE THREAD

**Issue by EzzahWaseem** [highcharts/highcharts-angular#260] opened 2021-01-11 11:01 UTC
Refer this issue [https://stackoverflow.com/questions/65665603/bar-high-chart-with-different-positive-and-negative-scale-interval-values](https://stackoverflow.com/questions/65665603/bar-high-chart-with-different-positive-and-negative-scale-interval-values)

**Comment by mateuszkornecki** [comment] 2021-01-11 11:20
Thanks for reporting the issue!

For the future please do not replicate the same questions over multiple contact channels to prevent situations when more than one highcharts developer is working on the same issue. Note that highcharts-angular/issues a place for reporting specific bugs related to the wrapper itself. For general support, questions contact us via one of the support channels (like stackoverflow), my colleagues responsible for them are monitoring all the questions so someone will definitely reply to you there.

Closing since it is a duplicate of https://stackoverflow.com/questions/65665603/bar-high-chart-with-different-positive-and-negative-scale-interval-values.

**Closed by mateuszkornecki** 2021-01-11 11:20 UTC
