### ISSUE TITLE
 problem "scrollablePlotArea" when updateFlag is true, Angular 7

### ISSUE THREAD

**Issue by ruiznaxo** [highcharts/highcharts-angular#137] opened 2019-04-29 20:09 UTC
When the updateFlag is true, the scroll does not work well

opacity
![image](https://user-images.githubusercontent.com/11983647/56923573-dbfee880-6a98-11e9-9ade-aec07989d529.png)

and fix yaxis
![image](https://user-images.githubusercontent.com/11983647/56923593-f0db7c00-6a98-11e9-9e29-d7b6ac881b82.png)

**Comment by jhonnyperezm** [comment] 2019-05-04 03:14
@ruiznaxo 

Hi, You have a link to the code, or a live demonstration

**Comment by KacperMadej** [comment] 2019-05-07 09:37
Hi @jhonnyperezm 

Thank you for contacting us about the problem.
Please add a live demo or chart's configuration and used Highcharts modules list, so we could recreate the problem and test possible solutions.

**Comment by KacperMadej** [comment] 2019-05-09 13:33
Please check if you could recreate the problem in pure Highcharts first - https://jsfiddle.net/BlackLabel/2oskxvyr/

Maybe it's caused by some missing chart configuration.

Please add a live demo or chart's configuration and used Highcharts modules list, so we could recreate the problem and test possible solutions.

**Comment by ruiznaxo** [comment] 2019-06-28 14:53
please check this https://stackblitz.com/edit/angular-apqfgu

click the button "change" to change series

**Comment by KacperMadej** [comment] 2019-06-30 13:23
This look like a general issue reported here: https://github.com/highcharts/highcharts/issues/8862

Using a known workaround it's possible to avoid the error in Angular by adding the workaround code in e.g. render event of a chart like this:

```
...
chart: {
events: {
        redraw: function() {
          // workaround start
  var chart = this,
    H = Highcharts,
    container = chart.container,
    fixedRenderer = chart.fixedRenderer;
  // These elements are moved over to the fixed renderer and stay fixed
  // when the user scrolls the chart.
  [
    chart.inverted ?
    '.highcharts-xaxis' :
    '.highcharts-yaxis',
    chart.inverted ?
    '.highcharts-xaxis-labels' :
    '.highcharts-yaxis-labels',
    '.highcharts-contextbutton',
    '.highcharts-credits',
    '.highcharts-legend',
    '.highcharts-subtitle',
    '.highcharts-title',
    '.highcharts-legend-checkbox'
  ].forEach(function(className) {
    H.each(chart.container.querySelectorAll(className), function(elem) {
      (
        elem.namespaceURI === fixedRenderer.SVG_NS ?
        fixedRenderer.box :
        fixedRenderer.box.parentNode
      ).appendChild(elem);
      elem.style.pointerEvents = 'auto';
    });
  });
...
```

**Comment by ruiznaxo** [comment] 2019-07-01 14:21
thanks it works, but in my real project it gives an error in the code and does not compile, as seen in the image. Please watch the demo and see the errors in app.component.ts, line 27 and 42

Demo: https://stackblitz.com/edit/angular-apqfgu

Images: 

![image](https://user-images.githubusercontent.com/11983647/60443723-cec1bf80-9be9-11e9-81df-7b90b1fd08b3.png)

![image](https://user-images.githubusercontent.com/11983647/60443682-b94c9580-9be9-11e9-830a-8c2790b97866.png)

Error in real project:
![image](https://user-images.githubusercontent.com/11983647/60443798-f9ac1380-9be9-11e9-8402-c1290891720a.png)

**Comment by KacperMadej** [comment] 2019-07-02 13:32
1. error is caused by using an internal method that is not documented and defined in TS. This could be resolved by extending TS definitions or by casting to `any` type to prevent this error from showing up.
`fixedRenderer = (chart as any).fixedRenderer;`

2. This was older version of Highcharts and you could try with code like
`chart.container.querySelectorAll(className).forEach(function (elem) {`
This might not work in all browsers, so in case it fails you could iterate the elements using any other way - e.g. though a `for` loop.

**Comment by ruiznaxo** [comment] 2019-07-03 21:28
Thank you very much, I would like you to continue helping me. I have two problems:
This error when the screen is greater than the minWidth:

![image](https://user-images.githubusercontent.com/11983647/60626069-94a61880-9db7-11e9-91da-d349a8a425d5.png)

And this when I have 2 Y axes in my real project:

![image](https://user-images.githubusercontent.com/11983647/60626096-af788d00-9db7-11e9-9a00-d6023f463904.png)

![image](https://user-images.githubusercontent.com/11983647/60626106-b6070480-9db7-11e9-8888-8f9edc6d5bf5.png)

**Comment by KacperMadej** [comment] 2019-07-15 13:35
It would be for the best if you could contact us through technical support channels, so you could get a better reply time. https://www.highcharts.com/blog/support/

I'm unable to recreate the problem.
Please recreate the problem in a live demo.

**Comment by ruiznaxo** [comment] 2019-07-15 14:01
the first problem is in this demo, look at the console: https://stackblitz.com/edit/angular-apqfgu
I will recreate the second problem

**Comment by KacperMadej** [comment] 2019-07-15 14:50
The error seems to be preventable by adding a check for `fixedRenderer` rest of the render event code as soon as the variable is set. So, add `if (fixedRenderer) {` before other code after `fixedRenderer` is set. I apologize for a lack of demo, but I have reached the limit of demos in that sandbox.

**Comment by ruiznaxo** [comment] 2019-07-22 17:42
Hi, here is the demo for second problem, click de "update chart" button. First problem was fixed thank to you.

https://stackblitz.com/edit/angular-pktlkh

**Comment by KacperMadej** [comment] 2019-07-23 13:50
Looks like the workaround is not that solid. In case there are multiple axes the query selector is not finding all elements correctly. A rather simple (over simplified and not universal) code that will work in your demo is like this:

```js
        redraw: function () {
          var chart = this,
            //H = Highcharts,
            container = chart.container,
            fixedRenderer = (chart as any).fixedRenderer;
          let a = [
            chart.inverted ? ".highcharts-xaxis" : ".highcharts-yaxis",
            chart.inverted
              ? ".highcharts-xaxis-labels"
              : ".highcharts-yaxis-labels",
            ".highcharts-contextbutton",
            ".highcharts-credits",
            ".highcharts-legend",
            ".highcharts-subtitle",
            ".highcharts-title",
            ".highcharts-legend-checkbox"
          ];

          if (chart.yAxis[1]) {
            a.push(
              chart.inverted
                ? ".highcharts-xaxis-labels"
                : ".highcharts-yaxis-labels",
              chart.inverted
                ? ".highcharts-xaxis"
                : ".highcharts-yaxis");
          }

          if (fixedRenderer) {
            for (let i = 0; i < a.length; i++) {
              for (
                let index = 0;
                index < container.querySelectorAll(a[i]).length;
                index++
              ) {
                let elem: any = chart.container.querySelectorAll(a[i])[index];
                (elem.namespaceURI === fixedRenderer.SVG_NS
                  ? fixedRenderer.box
                  : fixedRenderer.box.parentNode
                ).appendChild(elem);
                elem.style.pointerEvents = "auto";
              }
            }
          }
        }
```

**Comment by KacperMadej** [comment] 2019-07-23 13:56
Followup: Original workaround works for this case, so the `for` loop is flawed - it doesn't iterate correctly over all elements as it removes them and alters order loosing some of the elements.

**Comment by KacperMadej** [comment] 2019-08-13 09:34
Core problem is reported here: https://github.com/highcharts/highcharts/issues/8862
Closing as a duplicate.

**Closed by KacperMadej** 2019-08-13 09:34 UTC
Labels: Pending reply, Unable to recreate
