### ISSUE TITLE
Error: setOptions is not exported by node_modules/highcharts/highcharts.js

### ISSUE THREAD

**Issue by VikkySinghTanwer** [highcharts/highcharts-angular#242] opened 2020-11-26 07:19 UTC
Hi team, I am trying to bundle highchart along with the angular library using the dependencies in its package.json file. but when I am trying to bundle the library like ng build library-name its failing.

ERROR: 'setOptions' is not exported by node_modules\highcharts\highcharts.js, imported by dist\lib\ui\fesm5\lib-ui.js
An unhandled exception occurred: 'setOptions' is not exported by node_modules\highcharts\highcharts.js, imported by dist\lib\ui\fesm5\lib-ui.js

#### Expected behaviour
It should not complaint as code is already working fine, it only fails when I add this lib to dependencies of the lib package.json

#### Live demo with steps to reproduce
This is more on to the bundeling side not on the app running side. 

Here are the steps

1. create angular app -> ng new angular-app
2. install dependencies -> cd angular-app > npm install
3. create a library -> ng g library my-lib
4. install highcharts -> npm i highcharts --save
5. use highcharts.setOptions function in library main component.
   import * as Highcharts from 'highcharts';

   Highcharts.setOptions({
     lang: {
       thousandsSep: ","
     }
   });

6. add highchart as dependency in libraries package.json file
7. try building the library using ng build my-lib

#### Product version
I tries 8.0.4

**Comment by VikkySinghTanwer** [comment] 2020-11-26 13:58
> Hi @VikkySinghTanwer
> 
> Thank you for reporting this issue. I have created a new Angular application on my side and followed the steps that you provided and it seems that it works as expected (no errors). Could you provide a repository with a simplified project where this occurs?

sure, as I can not upload the repo due to some restrictions, I am giving a drive link to download it
https://drive.google.com/file/d/1cbFVdhRcS9uGTwoK3KSFBjevZfzx7yxi/view?usp=sharing
just try to run npm install and then ng build @trax/ui

**Comment by mateuszkornecki** [comment] 2020-11-27 07:38
Hello @VikkySinghTanwer,

I just tested the project you shared and I notice the following error: 
```bash
**WARNING: Inlining of 'bundledDependencies' has been deprecated in version 5 and will be removed in future versions.
List the depedency in the 'peerDependencies' section instead.
**
```

It seems that it was related to that because after I moved `highcharts` from the `bundledDependencies` to the `peerDependencies` I was able to build the package without any problems.

```json
// ui/src/package.json

{
  "name": "@trax/ui",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^9.0.7",
    "@angular/core": "^9.0.7",
    "highcharts": "^8.2.2"
  },
  "dependencies": {
    "ngx-color-picker": "^10.1.0",
    "highcharts": "^8.2.2"
  }
}
```

Let me know if the solution above does the job for you.

**Comment by VikkySinghTanwer** [comment] 2020-11-27 09:03
Hi @mateuszkornecki 

Thanks for trying it out, yes when I removes is from bundledDependencies is works fine. I am currently using inside dependencies of the libraries package.json. I am working on a mechanism using systemJS to only use bundled JS with all dependencies to make it work without bothering the parent app for an npm install or a release in future of there is any change in the library itself.

I am currently able to build is without having it in bundledDependeicies but not sure why it failed here where other packages are working fine.

Thanks 👍

**Comment by mateuszkornecki** [comment] 2020-11-27 10:06
I am glad it worked out for you! 😄 

Closing as it seems that the problem is resolved.

**Closed by mateuszkornecki** 2020-11-27 10:06 UTC
Labels: Pending reply
