### ISSUE TITLE
[oneToOne]-Directive fails on karma tests

### ISSUE THREAD

**Issue by tademeit** [highcharts/highcharts-angular#157] opened 2019-08-22 12:31 UTC
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
If you use the oneToOne-Directive within the highcharts-tag and you write a test within a component that uses the highcharts-oneToOne-directive it throws the following exception:

Binding to event property 'oneToOne' is disallowed for security reasons

In the application this error occures, too. But it works as intended.

We imported the HighchartsChartModule in our app.module.ts
### Expected behavior
The exception should not thrown.

### Demo
<highcharts-chart [Highcharts]="Highcharts"
                  [constructorType]="constructorType"
                  [options]="chartOptions"
                  [oneToOne]=true
                  [(update)]="updateFlag">
</highcharts-chart>

#### Steps required to recreate the problem in the demo:
1. Generate a spec file from that component and run the test

### Setup used
 - NodeJS version: 10.15.1
 - Angular version: 8.2.2
 - TypeScript version: 3.5.3
-  Highcharts-Angular: 2.4.0

**Comment by KacperMadej** [comment] 2019-08-23 09:29
Hi @tademeit 

Thank you for reporting about the problem.

Please check if this is not a duplicate of the https://github.com/highcharts/highcharts-angular/issues/60

(For me, it looks like it is.)

**Comment by tademeit** [comment] 2019-08-23 10:51
Hey @KacperMadej :
no it is not a duplicate. We already import the HighchartsChartModule in our app.module.ts.

**Comment by KacperMadej** [comment] 2019-08-23 12:03
The error comes from the lack of definition, so something is wrongly set up in the environment.
Please provide a way to recreate and debug the problem.

**Comment by KacperMadej** [comment] 2019-11-15 09:54
Closing due to inactivity.

**Closed by KacperMadej** 2019-11-15 09:54 UTC
Labels: Pending reply

**Comment by fallenreaper** [comment] 2020-03-20 18:19
I am getting this.  Has there been any sort of resolution, despite the HighChartsModule import not working?  I am trying to figure out how to suppress this "on*" issue.
