### ISSUE TITLE
Update Series dynamically when using 3d is not working

### ISSUE THREAD

**Issue by renatoly** [highcharts/highcharts-angular#50] opened 2018-07-18 08:35 UTC
I used to define the following chartOptions, with an empty series array:
```javascript
chartOptions = {
        title: {
            visible: false,
            text: ""
        },
        exporting: {
            enabled: false
        },
        credits: {
            enabled: false
        },
        xAxis: {
            visible: false
        },
        yAxis: {
            visible: false
        },
        labels: {
            visible: false
        },
        series: []
    };
```
Then after calling a service, I would get the entire options for the chart as json, including all series data, like this:

```javascript
getDashboardData(id: number): void {
        this.loading = true;
        this.dashboardService.getDashboard(id)
            .subscribe(dashboardData => {
                this.loading = false;
                this.chartOptions = dashboardData;
                this.updateFromInput = true;
            });
    }
```
When not using 3d, the chart updates dynamically with any amount of series returned by the service.
But when using 3d, the chart gives an error.

You can even try changing the chart's options  with an onclick handler instead of calling a service. 
for instance you can define the following variable, and then use it to set the chart's option binding property on your handler:  (You will see that when pepe.chart.options3d.enabled is true, the chart doesn't render)
```javascript
pepe:any = {
        title: {
            text: 'Month To Date Carrier Performance',
            visible: true,
            style: {
                fontSize: '16px',
                color: '#1c3660',
                fontFamily: 'Titillium Web'
            }
        },
        chart: {
            height: 500,
            backgroundColor: '#fff',
            type: 'column',
            plotBackgroundColor: 'rgb(255, 255, 255)',
            options3d: {
                skew3d: false,
                enabled: false,
                alpha: 15,
                beta: 0,
                viewDistance: 25,
                depth: 100
            }
        },
        credits: {
            enabled: false
        },
        xAxis: {
            categories: ["SAIA", "R&L Carriers"],
            visible: true,
            labels: {
                skew3d: false,
                style: {
                    fontSize: '13px',
                    color: '#1c3660',
                    fontFamily: 'Titillium Web'
                }
            },
            gridLineColor: '#bcf'
        },
        yAxis: [
            {
                visible: true,
                title: {
                    text: 'Count of Loads',
                    skew3d: false,
                    style: {
                        fontSize: '13px',
                        color: '#1c3660',
                        fontFamily: 'Titillium Web'
                    }
                },
                gridLineColor: '#bcf'
            },
            {
                visible: false
            },
        ],
        plotOptions: {
            series: {
                pointPadding: 0,
                groupPadding: 0.09
            },
            column: {
                stacking: 'normal',
                depth: 50
            },
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: true
            }
        },
        tooltip: {
            shared: true
        },
        labels: {
            visible: true
        },
        exporting: {
            sourceWidth: 1200,
            enabled: false
        },
        series: [{
            name: 'Loads with Issues',
            color: {
                linearGradient: {
                    x1: 0,
                    x2: 0,
                    y1: 0,
                    y2: 1
                },
                stops: [
                    [0, 'rgb(124,181,236)'],
                    [1, 'rgb(128, 203, 255)']
                ]
            },
            data: [208, 44],
        },
            {
            name: 'Loads without Issues',
            color: {
                linearGradient: {
                    x1: 0,
                    x2: 0,
                    y1: 0,
                    y2: 1
                },
                stops: [
                    [0, 'rgb(0, 63, 129)'],
                    [1, '#1c3660']
                ]
            },
            data: [472, 487],
        },
        {
            type: 'line',
            yAxis: 1,
            tooltip: {
                valueSuffix: '%'
            },
            name: 'Efficiency',
            data: [69, 92],
            marker: {
                lineWidth: 2,
                lineColor: '#1c3660',
                fillColor: 'white'
            }
        }
        ]
    };
```

**Comment by KacperMadej** [comment] 2018-07-18 11:45
Hi @renatoly 

Thank you for reporting about the problem. It looks like caused in the core Highcharts and not in the Angular wrapper. It's reported here: https://github.com/highcharts/highcharts/issues/8628

Please create a live demo that we could debug and test possible solutions or at least confirm that it's the same problem.

**Comment by renatoly** [comment] 2018-07-18 12:47
Hi, thank you very much for your prompt reply.  You are right, it seems a Highcharts issue.
Here is the demo: https://jsfiddle.net/renatoly/43wzkva5/1/.

I will report it on the highcharts forum.

Thanks a lot!

**Comment by KacperMadej** [comment] 2018-07-18 12:57
Duplicate of highcharts/highcharts#8628 - should be resolved when that issue will be resolved, so closing this issue.

**Comment by renatoly** [comment] 2018-07-18 12:58
Here is the issue: https://github.com/highcharts/highcharts/issues/8641

**Closed by KacperMadej** 2018-07-18 12:57 UTC
Labels: duplicate
