### ISSUE TITLE
Como puedo crear algo así ?

### ISSUE THREAD

**Issue by jhonnyperezm** [highcharts/highcharts-angular#125] opened 2019-03-21 17:22 UTC
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33642805/54771750-e8f40680-4bd3-11e9-8297-7d1d176ae86d.gif)
 
Como puedo enviar datos y quitarlos como se muestra en la imagen ?

**Comment by KacperMadej** [comment] 2019-03-22 14:40
Hola @jhonnyperezm  ,

The support is provided only in English, sorry.

With the highcharts-angular wrapper you could update series in chart options. For more info see here: https://github.com/highcharts/highcharts-angular#options-details (look for the chartOptions and updateFlag).

Alternative way could be to hide / show the series (like with the legend click). The Highcharts API for series.hide / series.show applies here (with the wrapper highcharts-angular). API reference:  https://api.highcharts.com/class-reference/Highcharts.Series#hide 
https://api.highcharts.com/class-reference/Highcharts.Series#show

In case of future questions please add a live demo and if you need technical support please contact us using: https://www.highcharts.com/blog/support/

The issue is not about a bug in the wrapper, so I'll close it for now.

**Closed by KacperMadej** 2019-03-22 14:40 UTC
