### ISSUE TITLE
Highcharts are creating design issues in Mi4i android mobile chrome browser and Hybrid app

### ISSUE THREAD

**Issue by kennedymca** [highcharts/highcharts-angular#7] opened 2017-12-12 09:21 UTC
We developed app using Highcharts with Angular. We have used standalone Highcharts( Piechart and Column chart). The problem here is there are some design issues when we load the highcharts. This issue occurs only in MI 4i mobile in both Chrome browser and hybrid app. Could you please check and let us know the issue?

Here i attached demo url: http://223.30.223.169/lrs/retailer/dist/index.html open this link in your Mi 4i mobile chrome browser, after you will see the design issues.

source code reference : https://github.com/kennedymca/angularhighcharts/tree/master/src/app

Chrome version: 61
Android version:5.0

**Comment by KacperMadej** [comment] 2017-12-12 16:14
"The problem here is there are some design issues when we load the highcharts. "
Please describe the problem - I do not know what to look for.

**Comment by kennedymca** [comment] 2017-12-13 10:07
We used Column and Pie charts in our application. When we access this page it works well in all mobiles except Mi 4i mobile.Please find below the screenshot which shows the issue. 
http://223.30.223.169/lrs/Screenshots/Chrome_browser.png
In the Column chart there are some black bar between the actual chart data. It is a design issue particularly in Mi 4i mobile

**Comment by KacperMadej** [comment] 2017-12-13 11:10
I tested this on Android 5.0 (through browserstack) and Android 6.0 using Chrome. I was not able to recreate the problem.

**Comment by kennedymca** [comment] 2017-12-13 11:14
you should check on Mi4i android mobile

**Comment by KacperMadej** [comment] 2017-12-13 12:19
Unfortunately I do not have this device. Highcharts are rendered in browser, so if there's a problem in a single device modele then this would suggest a problem in the device.

Just to be sure - the problem is visible only on the Xiaomi Mi 4i with Android 5.0.2?

I cannot see the relevant code for the app in the repo you linked in first comment - could you check that?

**Comment by kennedymca** [comment] 2017-12-13 12:40
The problem occurs in Mi 4i mobile's Chrome browser itself. The app is only a webview inside the native wrapper. So if we correct the issue in browser it should work in the app also.

**Comment by KacperMadej** [comment] 2017-12-13 13:22
@kennedymca We can prepare some demos for you to run on the Mi 4i to check where is the source of the problem. Please update your repo to show the code you are using and provide instructions for building the app, then we can test this on our end first - maybe the problem will be recreated and resolved without the need for advanced testing.

**Comment by kennedymca** [comment] 2017-12-14 07:06
Please share the demos. So that we can check here. And also the issue occurs in web app also. So you no need to create app. You can check on the browser first. If it works well in browser then we can check the same in the mobile app.

**Comment by KacperMadej** [comment] 2017-12-14 10:24
@kennedymca 
Ok, let's start with this repo - it has instruction and demo that you could test. Here's more info: https://github.com/highcharts/highcharts-angular#demo-app

After you will let me know if the same problem (or any other) is visible I will be able to prepare something more.

**Comment by kennedymca** [comment] 2017-12-14 13:06
I tried above repo it has only 2d chart, so try to change your little bit  below i attached that code, it shows only 2d chart, it won't show any 3d chart.

i imported 3d module in app.component.ts
import * as Chart3D from 'highcharts/highcharts-3d';
.
.
.
Chart3D(Highcharts);

`optFromInputString = {  "chart": {          "type": "pie",          "width": window.innerWidth - 20,          "options3d": {            "enabled": true,            "alpha": 45,            "beta": 0          }        },        "legend": {          "enabled": true,          "borderWidth": 2,          "layout": 'vertical',          "shadow": true        },        "credits": {          "enabled": false        },        "exporting": false,        "title": {          "text": "Invoice details"        },        "series": [{          "type": "pie",          "name": "Rs",          "data": [{"name":"SI-20Sep17-0000000065","y":24672.35},{"name":"SI-20Sep17-0000000064","y":979.4}]        }]		}
  optFromInput = this.optFromInputString;`

**Comment by KacperMadej** [comment] 2017-12-14 13:57
I wanted you to try a demo without 3d to try find source of the problem.
If you can please try to debug the problem to check what is the file that creates the problem.
If only 3d charts are affected, then it will be highcharts-3d module. Please check version you are using. Next step is to check if the 3d charts are displayed correctly without Angular on your device. Please check that and if there is a general problem with 3d charts and your device then the case will be moved to mail Highcharts github repository.

**Comment by kennedymca** [comment] 2017-12-14 14:24
I checked 3d chart that also working fine but i integrated only one chart on a screen, i want to implement more than one chart and i will let you know, really thank u  for supporting us

**Comment by kennedymca** [comment] 2017-12-15 13:03
i implemented 3d chart with angular that's working fine only chartoption value assigned in constructor(), if i assign the value from ngAfterViewInit() i am getting "series is undefiend" error, this error is coming from highcharts-chart.component.ts updateOrCreateChart() method in this line
 this.chart = this.Highcharts[this.constructorType || 'chart'](
        this.el.nativeElement,
        this.optionsValue,
        this.callbackFunction || null
      );

below i attached my code:

`declare var require: any
import { Component } from '@angular/core';
import * as Highcharts from 'highcharts/highstock';
import * as HC_exporting from 'highcharts/modules/exporting';
import * as HC_ce from 'highcharts-custom-events';
import * as Chart3D from 'highcharts/highcharts-3d';

HC_exporting(Highcharts);
HC_ce(Highcharts);
Chart3D(Highcharts);
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  Highcharts = Highcharts;
  so_chart_options: any;
  invoice_chart_options:any;
  top_prod_chart_options:any;
  updateFromInput: any;
  updateSO:boolean;
  updateSI:boolean;
  updateProd:boolean;
  ngAfterViewInit() {
    this.initializeChart();
  }
  
   initializeChart() {
     this.so_chart_options = {
        chart: {
          type: 'column',
          width: window.innerWidth - 20,
          options3d: {
            enabled: true,
            alpha: 10,
            beta: 25,
            depth: 70
          }
        }, tooltip: {
          formatter: function () {
            return '<b>' + this.series.name + '</b><br>₹' + this.y
          }
        },
        legend: {
          enabled: true,
          borderWidth: 2,
          layout: 'vertical',
          shadow: true,
        },
        plotOptions: {
          column: {
            pointPadding: 0.2,
            size: '95%',
            borderWidth: 0,
            events: {
              legendItemClick: function () {
                return false;
              }
            }
          },
          allowPointSelect: false,
        },
        credits: {
          enabled: false
        },
        exporting: false,
        title: {
          text: 'Order Details'
        },
        xAxis: {
          categories: ['']
        },
        yAxis: {
          title: {
            text: null
          }
        },
        showInLegend: false,
        series: [{"name":"SO-20Sep17-0000000048","data":[24672.35]},{"name":"SO-20Sep17-0000000047","data":[979.4]}]
      };

      this.invoice_chart_options = {
        chart: {
          type: 'pie',
          width: window.innerWidth - 20,
          options3d: {
            enabled: true,
            alpha: 45,
            beta: 0
          }
        },
        legend: {
          enabled: true,
          borderWidth: 2,
          layout: 'vertical',
          shadow: true
        },
        credits: {
          enabled: false
        },
        exporting: false,
        title: {
          text: 'Invoice details'
        },
        tooltip: {
          formatter: function () {
            return '<b>' + this.point.name + '</b><br>₹' + this.y
          }
        },
        plotOptions: {
          pie: {
            allowPointSelect: false,
            cursor: 'pointer',
            depth: 35,
            dataLabels: {
              enabled: false,
              format: '{point.name}'
            },
            showInLegend: true,
            point: {
              events: {
                legendItemClick: function (e) {
                  e.preventDefault();
                }
              }
            }
          }
        },
        series: [{
          type: 'pie',
          name: "Rs",
          data: [{"name":"SI-20Sep17-0000000065","y":20},{"name":"SI-20Sep17-0000000064","y":50}]
        }]
      };

      this.top_prod_chart_options = {
        chart: {
          type: 'pie',
          width: window.innerWidth - 20,
          options3d: {
            enabled: true,
            alpha: 45
          }
        },
        credits: {
          enabled: false
        },
        legend: {
          enabled: true,
          borderWidth: 2,
          layout: 'vertical',
          shadow: true
        },
        exporting: false,
        title: {
          text: 'Top Products'
        },
        plotOptions: {
          pie: {
            innerSize: 100,
            depth: 45,
            dataLabels: {
              enabled: false,
            },
            showInLegend: true,
            point: {
              events: {
                legendItemClick: function (e) {
                  e.preventDefault();
                }
              }
            }
          }
        },
        tooltip: {
          pointFormat: '<b>{series.name}.</b>{point.y}'
        },
        series: [{
          name: 'Delivered count',
          data: [{"name":"Choc. Horlicks 500gm Pet Jar","y":0},{"name":"DETANGLER 150 ML","y":0},{"name":"WHITE SOAP SUPER SAVER 300 GM","y":0},{"name":"GREEN SOAP 50 GM","y":0},{"name":"GREEN SOAP 100 GM","y":0}]
        }]
      };
  }
  
  updateChart() {
  
	this.invoice_chart_options.series[0].data= [{"name":"SI-20Sep17-0000000065","y":250},{"name":"SI-20Sep17-0000000064","y":152}];
      this.updateSI=true;
	  this.top_prod_chart_options.series[0].data =[{"name":"Choc. Horlicks 500gm Pet Jar","y":10},{"name":"DETANGLER 150 ML","y":5},{"name":"WHITE SOAP SUPER SAVER 300 GM","y":8},{"name":"GREEN SOAP 50 GM","y":4},{"name":"GREEN SOAP 100 GM","y":6}];
      this.updateProd=true;
	  
  }

}
`

**Comment by KacperMadej** [comment] 2017-12-15 14:29
@kennedymca 
What's the HTML template? I used
```
  template: `
	 <highcharts-chart 
	  [Highcharts]="Highcharts"
	  [options]="so_chart_options"

	  style="width: 100%; height: 400px; display: block;"
	></highcharts-chart>
	`,
```
and got error:
`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'.`

This is caused by your code that is using `ngAfterViewInit`. If I define the `so_chart_options` without using the `ngAfterViewInit` it's working fine.

**Comment by kennedymca** [comment] 2017-12-15 15:05
i want to call initializeChart() in ngAfterViewInit() method can you do that?

**Comment by kennedymca** [comment] 2018-01-03 09:43
What about that issue did you get any idea?

**Comment by KacperMadej** [comment] 2018-01-08 11:01
It's not possible due to the Angular error. Using that life cycle hook would cause infinite loop, because you are changing of the expression while it cannot be changed. You could try using different variables (that will be out of the check scope) or try setting the expression value to something that will not trigger the change check. Nested objects are not easily detected - usually this is a flaw, but in this case you could try using it as an advantage. In general I suggest resolving the problem that causes the error instead of just avoiding the error display/catch, but if you want to do this then I cannot stop you.

**Comment by KacperMadej** [comment] 2018-02-06 11:52
Closing due to inactivity. Please provide more info and the issue can be reopened. If you require technical support please contact support: https://www.highcharts.com/support

**Closed by KacperMadej** 2018-02-06 11:52 UTC
Labels: Unable to recreate
