### ISSUE TITLE
How to use solid gauge chart

### ISSUE THREAD

**Issue by tstreamDOTh** [highcharts/highcharts-angular#67] opened 2018-09-06 07:22 UTC
I am getting error#17 for chart type: 'solidgauge',

**Comment by sebastianbochan** [comment] 2018-09-06 08:45
Hi @tstreamDOTh,
Thank you for reporting. It looks like duplicate of https://github.com/highcharts/highcharts-angular/issues/59.

If problem is different, please supply us a code and reopen the case.

**Closed by sebastianbochan** 2018-09-06 08:45 UTC

**Comment by tstreamDOTh** [comment] 2018-09-06 10:11
@sebastianbochan  Thanks. It helped.
