### ISSUE TITLE
Type errors. 'TooltipPositionerPointObject' should extend 'Point'

### ISSUE THREAD

**Issue by snattie** [highcharts/highcharts-angular#211] opened 2020-07-14 10:50 UTC
There are type errors in tooltip `positioner` function :
```{ 
tooltip: {
  positioner(width: number, height: number, point: TooltipPositionerPointObject): {x: number; y: number} {
    // ...
  }
} 
```

Error messsage:
TS2322: Type '(width: number, height: number, point: TooltipPositionerPointObject) => { x: number; y: number; }' is not assignable to type 'TooltipPositionerCallbackFunction'.   Types of parameters 'point' and 'point' are incompatible.     Type 'Point' is missing the following properties from type 'TooltipPositionerPointObject': isHeader, negative, plotX, plotY.

Creating own interface extending 'Point' object solves the problem.

**Comment by mateuszkornecki** [comment] 2020-07-14 11:24
Thanks for reporting the issue @snattie .

It is happening because `TooltipPositionerPointObject` is not the correct type in that case. As you can see in the API, the correct type for the point is `Highcharts.Point | Highcharts.TooltipPositionerPointObject`. Updating its type should fix the problem as well. 

**API references:**
https://api.highcharts.com/class-reference/Highcharts#.TooltipPositionerCallbackFunction

**Live demo:**
https://stackblitz.com/edit/highcharts-angular-basic-line-bfntxf

For the future - for general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

Closing since it is not a bug.

**Closed by mateuszkornecki** 2020-07-14 11:24 UTC
