### ISSUE TITLE
Angular Ivy

### ISSUE THREAD

**Issue by r-havelka** [highcharts/highcharts-angular#161] opened 2019-09-10 18:50 UTC
Upgrade highcharts-angular to angular 8 and have the project be ivy compatible.

https://angular.io/guide/ivy

**Comment by KacperMadej** [comment] 2019-09-11 10:55
Currently, Ivy is available as a preview.
In case of problems please describe them - start with trying to resolve it through technical support.
When Ivy will be available not as a preview then an option for an additional demo or a current demo app update will be investigated again.

**Comment by ghoyle** [comment] 2019-09-25 10:43
When I've tried to update AngularCLI I get an error message saying a dependency in angular-highcharts is incompatible so it cant update

**Comment by KacperMadej** [comment] 2019-09-25 12:30
Are you sure about the errors with `angular-highcharts`? Because this is not the correct repo for that component.

**Comment by shravansofts** [comment] 2019-11-06 05:42
I'm trying to upgrade from angular 8.2.13 to angular 9
This is the error we are facing.
![image](https://user-images.githubusercontent.com/12848838/68271360-3ac79f00-0086-11ea-8277-de90ee6c5cb4.png)
Please suggest

**Comment by KacperMadej** [comment] 2019-11-06 16:15
Hi @shravansofts 

You are testing a release candidate of Angular, so this might be a problem for the versions to not be recognized correctly. The peer dependencies should require version of at least 2.0.0, so 9+ should be accepted as well. I'm not sure how should the peer dependencies be set to allow `rc` versions.

You could try manually changing the peer dependencies manually in the installed node_modules directory for the Highcharts wrapper, so they will match your Angular version or at least won't rise any errors. In reality, only the Highcharts package is a must-have, so you could try removing them altogether from the peerDependencies in the package.json.

If this won't help or if the problem will be visible on a non-rc release of Angular then we could search for a permanent solution for this wrapper.

**Comment by SchnWalter** [comment] 2020-01-16 18:21
I've just tested the library with Ivy v9 and it works in our situation.

And KacperMadej is right about the `ng update` error, Angular hasn't been released yet, but there is nothing stopping you from testing the application and making sure it works when Angular v9 is released.

**Comment by romainmoreau** [comment] 2020-02-07 09:53
I have noticed a regression with Ivy and the `callbackFunction` option.

The function is not called when Ivy is enabled ([demo](https://github.com/romainmoreau/highcharts-angular9)).

When `enableIvy` is set to [false](https://github.com/romainmoreau/highcharts-angular9/blob/6b32b17fd32133469227a80976e1e7f20a8719b1/tsconfig.json#L25), the function is called like before with Angular 8.

**Comment by LuukMoret** [comment] 2020-02-10 11:08
We are experiencing the same issue any workaround for now would be great.

**Comment by MaxSassen** [comment] 2020-02-10 13:26
> I have noticed a regression with Ivy and the `callbackFunction` option.
> 
> The function is not called when Ivy is enabled ([demo](https://github.com/romainmoreau/highcharts-angular9)).
> 
> When `enableIvy` is set to [false](https://github.com/romainmoreau/highcharts-angular9/blob/6b32b17fd32133469227a80976e1e7f20a8719b1/tsconfig.json#L25), the function is called like before with Angular 8.

Seems like the callbackFunction is always undefined when Ivy is enabled.

**Comment by stevethemacguy** [comment] 2020-02-12 02:27
Here's Google's tool to help library authors conform to the Angular Package Format:

https://github.com/ng-packagr/ng-packagr
https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

The official HC plugin didn't exist when we started our app, so we use angular2-highcharts, but it's no longer maintained and doesn't support IVY, so we're hoping to switch to highcharts-angular. Fingers crossed for IVY support! Thank you!

**Comment by Geoffrynagy** [comment] 2020-02-17 07:54
We are experiencing the same behaviour, is any fix or workaround present?
The missing callbackFunction is preventing us from upgrading to angular 9.

**Comment by MaxSassen** [comment] 2020-02-17 13:28
Totally missed the output param:
` @Output() chartInstance = new EventEmitter<Highcharts.Chart>(); // #26`

This can replace the `callbackFunction` to retrieve the chart.
But I suggest to remove the `callbackFunction` from the input ( it doesn't work anyway)

**Comment by KacperMadej** [comment] 2020-02-17 16:27
I have debugger Angular 9 demo provided by @romainmoreau - thank you for the demo. The `callbackFunction` is missing due to the inputs loading order - if you will set the HTML props order so that the options will be last then all other properties will be loaded before the chart will be created and all should work fine.

The properties order should be changed so `options` (chart's options) will be loaded last always (at very least the last input) and info should be added to the docs. This won't break anything in pre-9 versions of Angular and should resolve the problem in v9+.
fyi: @kamilkulig

**Comment by romainmoreau** [comment] 2020-02-17 23:01
Thanks for investigating @KacperMadej. To my understanding, relying on the order of inputs isn't a good practice. Instead, `ngOnChanges` should be used to handle dependencies between inputs.

Also, @MaxSassen has a point: why is there both `callbackFunction` and `chartInstance`?
Don't these properties have the same purpose?

**Comment by KacperMadej** [comment] 2020-02-18 10:17
@romainmoreau It looks to me that [`ngOnChanges`](https://angular.io/api/core/OnChanges) won't resolve the problem with not knowing if potentially optional inputs will be loaded since they are loaded one by one in the order of the HTML template. Could you elaborate on this?
___
**Don't  `callbackFunction` and `chartInstance` have the same purpose?**

Could have, but are not exactly the same.
* `callbackFunction` is a function that will be executed with the context of the chart (unless you override the default context, like with usage of a fat arrow function) and will have the chart as the first and only argument. This is an input of the component.
* `chartInstance` is the chart - the variable will be emitted as an output.

See also: https://github.com/highcharts/highcharts-angular#chart-instance

(Personally I am finding this rather redundant, but it was requested by some users and I am sure that I don't know everything, so it was added.)

**Comment by romainmoreau** [comment] 2020-02-18 13:12
@KacperMadej on template initialization, `ngOnChanges` is called only once and all the inputs are present in the `SimpleChanges` parameter. Here's a [commit](https://github.com/romainmoreau/highcharts-angular/commit/c059eb57ab9601215b8f1565bbc5ef0155100edf) where `ngOnChanges` is used instead and with it, the order of the inputs doesn't matter anymore.

**Comment by KacperMadej** [comment] 2020-02-18 13:54
@romainmoreau This looks very nice, thank you so much.

_Internal note:_
We should definitely use this to resolve the problem. (unless of course, after further tests something problematic will pop-up)
I'm relabelling this to a bug since Angular v9 is having significant issues with this.
fyi: @kamilkulig

**Comment by stevethemacguy** [comment] 2020-02-21 04:14
@KacperMadej. Sorry if this is overstepping, but I wanted to confirm that @romainmoreau's fix works for our application (which has 80+ chart instances). I checked out his ng-on-changes branch, built the highcharts-angular library locally, and our charts now work in production with IVY enabled. Would love to see a PR for this if it passes other tests! Thank you!

**Comment by stevethemacguy** [comment] 2020-03-11 02:56
@KacperMadej Any update on this? It's not feasible to keep manually patching our app. This is the only dependency that's blocking us on Angular 9. Thank you. @romainmoreau, can you submit a PR? Thank you.

**Comment by zkozniak** [comment] 2020-03-11 10:59
Waiting for this fix too, 10x!

**Comment by ehsantoucerkany** [comment] 2020-03-30 08:34
Would really appreciate if there was some progress here. Thank you.

**Comment by Phazzer** [comment] 2020-04-27 07:11
Please implement the fix! Thanks!

**Comment by obsd** [comment] 2020-05-04 16:55
We are working with Highcharts at my company [paid enterprise version] and we want to update to angular 9 is there any estimation for the resolution of this?

**Comment by MaxSassen** [comment] 2020-05-05 06:01
> Please implement the fix! Thanks! We need to use angular 9 very soon

> We are working with Highcharts at my company [paid enterprise version] and we want to update to angular 9 is there any estimation for the resolution of this?

We already are working with highchart and ivy for a couple of months and have no other issue than this one .. but as mentioned before.. using:

```@Output() chartInstance = new EventEmitter<Highcharts.Chart>(); // #26```

Solved that little problem. And as @KacperMadej mentioned before this the same as using callBackFunction (and way cleaner in my opinion).

You shouldn't wait too long for this fix, the longer you wait for upgrading to angular 9 the more refactoring you must do.

**Comment by obsd** [comment] 2020-05-11 17:24
@MaxSassen  can you explain what exactly you did?
did you use this commit?
https://github.com/romainmoreau/highcharts-angular/commit/c059eb57ab9601215b8f1565bbc5ef0155100edf

**Comment by stevethemacguy** [comment] 2020-05-11 18:35
I forked the highcharts-angular library with @romainmoreau's ngOnChanges fix to get the charts working again on our project. For anyone needing a workaround, you can **temporarily** point to my forked repo when installing the npm package instead of using the offical highcharts-angular library. 

**WARNING:** This is a forked repo on my personal GitHub account. I recommend that you fork the branch yourself instead of using mine. Once the official plugin is fixed, I will take this branch down and your production build will break. I am not associated with the angular-highcharts, highcharts, or angular teams in any way and I cannot verify that romainmoreau's fix won't break something else. 

With that said, our app now builds with the IVY AOT compiler and works. At the very least, it should help you move forward with development until the library authors fix the bug.

Note: My branch has _not_ been published on the NPM repository. If you have successfully pointed to my repo (or your own forked version), your package.json file will look something like this:

"highcharts-angular": "git://github.com/stevethemacguy/highcharts-angular-fork.git",

My Forked Branch
https://github.com/stevethemacguy/highcharts-angular-fork

Good luck!

**Comment by jakkn** [comment] 2020-06-03 08:44
Pinging @kamilkulig @KacperMadej as highcharts representatives previously mentioned in this thread.

Is there any chance we can get an official update on where the project stands on this issue? There are multiple companies and people waiting for this change and the lack of communication is driving people to maintain unofficial forks. Please consider prioritizing this issue.

**Comment by Phazzer** [comment] 2020-06-08 08:29
@KacperMadej , our management here is worried that Highcharts' lack of response on this issue indicates Highcharts is lowering your support/interest in Angular. That makes it difficult to justify my preferred choice of future technology. Maybe this information can help you to convince *your* management to increase priority...

**Comment by omnibrain** [comment] 2020-06-08 09:16
Have you all seen this comment (https://github.com/highcharts/highcharts-angular/issues/161#issuecomment-586993654):


> Totally missed the output param:
> ` @Output() chartInstance = new EventEmitter<Highcharts.Chart>(); // #26`
> 
> This can replace the `callbackFunction` to retrieve the chart.
> But I suggest to remove the `callbackFunction` from the input ( it doesn't work anyway)

We've migrated to Angular 9 with Ivy months ago using this output. Works like a charm. Does that justify removing the callbackFunction input for no apparent reason and not responding to any clients relying on this Angular wrapper? Not really, but at least there's a solution.

**Comment by Phazzer** [comment] 2020-06-08 09:29
jvinther@eso.org

**Comment by Phazzer** [comment] 2020-06-08 09:44
Yes, I have seen it and indeed it solves the technical issue. We are worried that the official support for the Highcharts/Angular wrapper is being abandoned. No response for months.

**Comment by mateuszkornecki** [comment] 2020-06-08 11:26
I can confirm the wrapper is not abandoned and we are constantly providing support for it.

We have already started working on the official fix. Please be patient, as soon as a ready solution appears, it will definitely be noted in this topic.

**Comment by AdaskoTheBeAsT** [comment] 2020-07-01 13:39
Hi,

patch will be also compatible with angular 10?

**Comment by mateuszkornecki** [comment] 2020-07-02 05:36
The upcoming release of the wrapper will fix the compatibility problems with angular 9. As far as angular 10 didn't introduce many significant changes, so the wrapper might work correctly with it - however, we need to do some testing to be 100% sure.

**Comment by Nosfistis** [comment] 2020-07-06 08:49
Angular 10 has not many significant changes, however there are warnings related to the bundling.
```
CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
This might be better related to https://github.com/highcharts/highcharts/issues/12738, which relates to current modules, but I thought it should be mentioned here as well.

**Comment by shravansofts** [comment] 2020-07-16 15:21
Angular 10 also released. You people still not able to support Angular 9.
we are getting questioned for the choice made on highcharts? :(

Very much disappointed with the response even after paying for licensing and seeing lack of tooling and support for  modern JS frameworks.

**Comment by mateuszkornecki** [comment] 2020-07-17 10:01
Thank you for sharing your opinion! The new version is already finished, and it should be released in the next week. After release, you will find updated demos and additional live-examples in the docs. 

Most of the differences between highcharts in vanilla JS and highcharts-angular are related to chart updates. You can create the drilldown in the same way as in the "regular" highcharts. An article about drilldowns is available in the highcharts docs, here: https://www.highcharts.com/docs/chart-concepts/drilldown.

This repository is mainly focused on the `highcharts-angular` wrapper features - that's why you couldn't find a drilldown example here. If you would like to see the example that is not shown here just contact us through one of the support channels, we will be happy to help you!
https://www.highcharts.com/blog/support/

**Comment by mateuszkornecki** [comment] 2020-07-23 14:20
Closing since the new version was released today.

**Comment by stevethemacguy** [comment] 2020-07-23 22:57
Glad to see the PR finally approved, but there's no mention of it in the changelog.

**Comment by dilotec-2015** [comment] 2020-08-27 18:29
Ivy ist still not working for me

**Comment by mateuszkornecki** [comment] 2020-08-31 12:48
@stevethemacguy 
Sorry for the late reply. We had some minor issues while releasing the previous version, the corrected changelog will be released in the upcoming version.

@dilotec-2015  Could you reproduce the issue in an online editor (like stackblitz) that I could work on? It would be much easier to investigate the problem and find a proper solution with the access to your code.

**Comment by SomethingNew71** [comment] 2020-09-02 13:42
We are also seeing this issue still in our Angular 9 application. 

```
This likely means that the library (highcharts-angular) which declares HighchartsChartComponent has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
4 export declare class HighchartsChartComponent implements OnDestroy, OnChanges {
                       ~~~~~~~~~~~~~~~~~~~~~~~~
An unhandled exception occurred: node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts:4:22 - error NG6002: Appears in the NgModule.imports of LibFinancialPlanningModule, but could not be resolved to an NgModule class.
```

**Comment by mateuszkornecki** [comment] 2020-09-03 05:39
@SomethingNew71 

Would you mind reproducing the issue in a simple demo that I could test? I can see that some users are facing problems with ivy, but I was never able to reproduce it on my own.

**Comment by mateuszkornecki** [comment] 2021-01-04 09:10
Closing due to inactivity.

**Closed by mateuszkornecki** 2021-01-04 09:10 UTC
Labels: Unable to recreate
