### ISSUE TITLE
`fillColor` stops working after url changed

### ISSUE THREAD

**Issue by JounQin** [highcharts/highcharts-angular#245] opened 2020-12-07 05:08 UTC
### Describe the bug

`fillColor` setting of series stops working

### Expected behavior

`fillColor` should continue work on route changes

### Demo

https://stackblitz.com/edit/highcharts-angular-basic-line-g9xaw3?file=src%2Fapp%2Ftest%2Fcomponent.ts

#### Steps required to recreate the problem in the demo:

Just click the `Test` link, url will change, and `fillColor` will disappear

### Setup used
 - NodeJS version: v12.20.0
 - Angular version 10.2.0
 - TypeScript version 4.0.5

**Comment by pawelfus** [comment] 2020-12-07 10:00
Hi @JounQin 

Thanks for reporting the issue. This is a duplicate of #102, or rather a bug in the core: https://github.com/highcharts/highcharts/issues/5244

The temporary workaround is posted here: https://github.com/highcharts/highcharts/issues/5244#issuecomment-214674124

Closing as duplicate of https://github.com/highcharts/highcharts/issues/5244

**Closed by pawelfus** 2020-12-07 10:00 UTC
