### ISSUE TITLE
Trend line gets distorted on moving multiple times

### ISSUE THREAD

**Issue by officesyncpersonal** [highcharts/highcharts-angular#295] opened 2021-07-19 14:48 UTC
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
Trend line should maintain its slop and move as if we are moving a physical line.

### Expected behavior
Trend line losses its slop. A slanting lines gets converted into straight line.

### Demo
![HighchartIssue](https://user-images.githubusercontent.com/83967360/126179242-3caaef47-4bf3-4970-9713-6b7474e45352.gif)

#### Steps required to recreate the problem in the demo:
You can use any live demo hosted by you. Just follow these steps:
#1. draw a trend line or vertical label.
#2. Start moving it across chart, multiple time,

### Setup used
 - NodeJS version:  latest
 - Angular version: latest ["@angular/core": "~12.1.2",]
 - TypeScript version: latest ["tslib": "^2.3.0",]
 - "highcharts": "^9.1.2",
 - "highcharts-angular": "^2.9.0",

**Comment by officesyncpersonal** [comment] 2021-07-19 14:54
Interesting part is all your demos have same issue. Whereas other charting library like tradingView seems to work fine.

**Comment by karolkolodziej** [comment] 2021-07-19 14:58
Duplicate of [this issue](https://github.com/highcharts/highcharts/issues/15970), will be solved by [this PR](https://github.com/highcharts/highcharts/pull/15987).

**Closed by karolkolodziej** 2021-07-19 14:58 UTC
