### ISSUE TITLE
Highcharts.Options with ngx-translate

### ISSUE THREAD

**Issue by Th4nhT0m** [highcharts/highcharts-angular#371] opened 2023-12-26 02:45 UTC
I am having a problem using @ngx-translate for Highcharts.Options. When I change the language, I have two problems:
 - First, when I set the translation into Highcharts.Options.series.name, it does not work.
 - Second, when I set Highcharts.Options.lang, it does not change to the language I want when translate (lang not change ).
 
 I am using highcharts version: 11.2.0 and highcharts-angular : 3.0.0

 Here is my code:
-------------------------------------------------------
// Highcharts
import * as  Highcharts from 'highcharts';
import exporting from 'highcharts/modules/exporting';
import exportData from "highcharts/modules/export-data";

exporting(Highcharts);
exportData(Highcharts);

//Service
import { TranslateService } from '@ngx-translate/core';

-------------------------------------------------------
    highcharts: typeof Highcharts = Highcharts;
    chartOptions: Highcharts.Options;

    constructor(
        public translate: TranslateService
    ) {
        super();
        //Get the event to change the language
        this.translate.onDefaultLangChange.pipe(takeUntil(this.componentDestroyed$))
        .subscribe(() => { // problems 2
            this.chartOptions.lang.viewFullscreen = this.translate.instant('Label.FullScreenMenu');
            this.chartOptions.lang.exitFullscreen = this.translate.instant('Label.FullScreenExitMenu');
            this.chartOptions.lang.downloadCSV = this.translate.instant('Label.CsvDldMenu');
            this.chartOptions.lang.downloadSVG = this.translate.instant('Label.ImgDldMenu');
        });
    }
-------------------------------------------------------
    ngOnInit(): void {
        this.setHighChartOptions();
    }

    setHighChartOptions() {
        this.chartOptions = {
             series: [
                        //Set data series
                        {
                            name: this.translate.instant('Label.Process'), // problems 1
                            data: this.list.map(item => item.size),
                            type: 'column',
                        },
                    ],
                        lang: { // problems 2
                            viewFullscreen: this.translate.instant('Label.FullScreenMenu'),
                            exitFullscreen: this.translate.instant('Label.FullScreenExitMenu'),
                            downloadCSV: this.translate.instant('Label.CsvDldMenu'),
                            downloadSVG: this.translate.instant('Label.ImgDldMenu'),
            }
 }

**Comment by karolkolodziej** [comment] 2023-12-27 10:06
Hi @Th4nhT0m!

From your code, it isn't that obvious how you change the options/lang. Could you please edit [the demo I've prepared](https://stackblitz.com/edit/highcharts-angular-line-ber22x?file=src%2Fapp%2Fapp.component.ts) so the issue is visible?

**Comment by Th4nhT0m** [comment] 2023-12-27 11:20
Hi,[@karolkolodziej](https://github.com/karolkolodziej) 
Thanks for answering
I just edited the demo but the translate.instant part in the demo has a problem and cannot get the language. It's different from the problem I need help with: when I change the language, the language in my HighCharts doesn't change to the fr language.[Here is the demo I edited](https://stackblitz.com/edit/highcharts-angular-line-b5o14q?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fassets%2Fi18n%2Ffr.json,src%2Fassets%2Fi18n%2Fen.json)

**Comment by karolkolodziej** [comment] 2023-12-28 07:01
Thanks for the update- now everything is clear! 

I'm not super familiar with the `@ngx-translate/core` but it looks like some of the stuff there is asynchronous. 
Quote from their documentation regarding the `instant` method:
> instant(key: string|Array<string>, interpolateParams?: Object): string|Object: Gets the instant translated value of a key (or an array of keys). /!\ This method is synchronous and the default file loader is asynchronous. You are responsible for knowing when your translations have been loaded and it is safe to use this method. If you are not sure then you should use the get method instead.

So:
1. **Initial render-** _First, when I set the translation into Highcharts.Options.series.name, it does not work._
It is because you are trying to set the translation when it isn't available yet. 
If you execute it when you have it, everything works as expected.

2. **Update-** _Second, when I set Highcharts.Options.lang, it does not change to the language I want when translate (lang not change )._
Here we have two issues: 
    - With `this.translate.instant('key')` you are trying to access something that isn't available yet. I work around it by putting everything into the `setTimeout`. Very brutal but works 😅 To be clear, this probably isn't the recommended solution.
    - The `upateFlag` is missing, you need to add it and set to true when updating anything in the `chartOptions` to let know the component about the change so it can update itself. 

[Demo with my changes](https://stackblitz.com/edit/highcharts-angular-line-lrqbfg?file=src%2Fapp%2Fapp.component.ts)
It works but the solutions there are far from ideal, please check the `ngx-translate` maybe there you can find a better approach. The `get` method looks promising.

As far as I see there is nothing wrong with the `highcharts-angular` integration so I'm going to close it for now. 
If you have any other issues or questions feel free to ask them 😉

**Closed by karolkolodziej** 2023-12-28 07:01 UTC
Labels: Pending reply

**Comment by Th4nhT0m** [comment] 2024-01-04 02:54
Thank you very much [karolkolodziej](https://github.com/karolkolodziej)
I'm understanding my problem
