### ISSUE TITLE
Receiving error (Error: <rect> attribute height: Expected length, "4.31302272327349…") while feeding live data 

### ISSUE THREAD

**Issue by brijeshpant83** [highcharts/highcharts-angular#207] opened 2020-06-30 04:12 UTC
![Screenshot 2020-06-30 at 9 38 52 AM](https://user-images.githubusercontent.com/42262135/86082743-22454280-bab6-11ea-84c9-c2c4dc94f745.png)
Receiving this error while feeding live data, please help to resolve this.

Error in console.
![Screenshot 2020-06-29 at 5 00 31 PM](https://user-images.githubusercontent.com/42262135/86082687-fc1fa280-bab5-11ea-95b3-2b44332cccf3.png)

Error: <rect> attribute height: Expected length, "4.31302272327349…".

**Comment by mateuszkornecki** [comment] 2020-06-30 08:46
Thanks for reporting the issue @brijeshpant83.

Could you reproduce the issue in an online editor so I can check if that's related to the highcharts-angular wrapper? Without access to your code, it is hard to tell you what is not working or what could be done.

 Also what version of the highcharts + highcharts-angular are you currently using?

**Comment by brijeshpant83** [comment] 2020-07-01 07:16
Actually this is working normally, but when I am feeding live data per second through socket that it appearing. My initial finding is when we are plotting line chart in limited area like 10% of screen or somewhere on animation.
Here is sample push code which is running inside loop (number of charts)
let eachtime = new Date(feedData['TIMESTAMP']).getTime();
              let eachTagValue = feedData['tag_value'];
              eachTagValue = Number(eachTagValue.toFixed(2));
              let shift = this.eachChartObject[colindexkey].chartObj['series'][key].options.data.length > 500;
              this.eachChartObject[colindexkey].chartObj['series'][key].addPoint([eachtime, eachTagValue], true, shift);

**Comment by mateuszkornecki** [comment] 2020-07-01 09:27
Unfortunately, I am unable to recreate the issue without your demo. Could you tell me how often you are adding new data to the chart? I have seen similar issues in the past and it was occurring for the interval below 1000ms only.

**Comment by brijeshpant83** [comment] 2020-07-02 04:34
almost every second in all the charts which are present on one page.

**Comment by mateuszkornecki** [comment] 2020-07-02 10:29
It sounds like a regression bug that has been recently reported in the highcharts repo. You can find more details about it on the highcharts issue page, here: https://github.com/highcharts/highcharts/issues/13437.

Since it seems that the bug is not related to the highcharts-wrapper but to the highcharts itself I am closing the issue.

**Closed by mateuszkornecki** 2020-07-02 10:29 UTC
Labels: Pending reply, Unable to recreate

**Comment by brijeshpant83** [comment] 2020-07-29 12:13
yes its a highchart issue, for the being time it can be resolved by delay in update.
