### ISSUE TITLE
Incorrect rendering of Gantt chart after data updating

### ISSUE THREAD

**Issue by sequent** [highcharts/highcharts-angular#169] opened 2019-12-02 19:00 UTC
I work with data visualization on related diseases and targets. I have an array of associated data that is filtered to display in the Gantt Chart depending on the options selected.

My question also published on [stackoverflow](https://stackoverflow.com/questions/59138523/incorrect-rendering-of-gantt-chart-after-data-filtering-in-angular7)

#### Expected behaviour
When working with only one filter, everything works correctly.

#### Actual behaviour
 I got a problem when the data loaded in the series.data but some are not displayed. 

#### Live demo with steps to reproduce

Demo: [codesandbox](https://codesandbox.io/s/angular-k4xio
)
#### Product version

"@angular/common": "^7.2.3",
"@angular/compiler": "^7.2.3",
"@angular/core": "^7.2.3",
"@angular/forms": "^7.2.3",
"highcharts": "^7.2.1",
 "highcharts-angular": "^2.4.0"

#### Affected browser(s)
Any browser

**Comment by pawelfus** [comment] 2019-12-03 11:14
Duplicate of #12545 

@sequent - please, don't create ticket in every repo.

**Closed by pawelfus** 2019-12-03 11:14 UTC
Labels: duplicate
