### ISSUE TITLE
Chart doesn't fit the parent container, too big for the device size (Ionic App)

### ISSUE THREAD

**Issue by vidhi-mistry** [highcharts/highcharts-angular#204] opened 2020-06-23 14:46 UTC
I am using highcharts in Ionic 5 app and I am using high-charts angular library. On the first load of the page, the chart doesn't fit properly on the device screen. Here is the output I get :

![issue](https://user-images.githubusercontent.com/40681317/85416591-a2126080-b53c-11ea-93de-c2357e1004fd.JPG)

But when I try to change the screen size, it snaps back to appropriate width of the device and the chart gets displayed correctly.

I tried following the suggested [solution](https://github.com/highcharts/highcharts-angular/issues/149#issuecomment-508692517) but the graph didn't get displayed at all for me. 

**Complete code :** 
https://github.com/vidhi-mistry/ionic-highcharts

**Setup :** 
Ionic:

   Ionic CLI                     : 5.4.16 
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : 0.15.0
   native-run  : 1.0.0

System:

   NodeJS : v12.17.0 
   npm    : 6.14.4

****Highcharts:
  highcharts : v8.1.2
  highcharts-angular : v2.0.4****

**Comment by mateuszkornecki** [comment] 2020-06-24 09:38
Hi, @vidhi-mistry thanks for reporting the problem.

Could you reproduce the issue in an online editor that I could work on? It will be much easier to check what is not working or what could be done with access to the simplified demo. 

You can start from this template: https://stackblitz.com/edit/highcharts-angular-basic-line

**Comment by vidhi-mistry** [comment] 2020-06-24 19:10
Having the highcharts element placed inside a div element might recreate the problem I am facing, but I am not sure if that that's the actual issue in the Ionic setting. Please follow this link : https://stackblitz.com/edit/highcharts-angular-basic-line-xfgwm1
If the page is opened in new window and device is changed to any of the mobile sizes, we see that the graph is initialized to width of 600px, even though the width of the parent container is less. I want the graph to take up the width of the parent container i.e div. So that it fits the device size.

Setting width to 100% to the highcharts container makes the graph to be displayed correctly for all device sizes on loading. However, this fix (setting highchart's element's width to 100%) **doesn't work in the ionic app** and the graph always takes up 600px on the first load irrespective of the device's screen width. That's why I have provided a starter code in ionic : https://github.com/vidhi-mistry/ionic-highcharts.

**Comment by mateuszkornecki** [comment] 2020-06-25 11:07
I cloned your repository and managed to fix the problem using the https://github.com/highcharts/highcharts-angular/issues/149#issuecomment-508692517 solution. Basicly all you need to do is to call chart.reflow() inside the `[chartCallback]`

```javascript
  chartCallback: Highcharts.ChartCallbackFunction = function (chart): void {
        setTimeout(() => {
            chart.reflow();
        },0);
    }
```

Keep in mind that because of https://github.com/highcharts/highcharts-angular/issues/161 the order of the inputs matters while working in Angular 9 (just place `[callBackFunction]` above the `[chartOptions]`). The fix of that bug is almost ready, so after the incoming release, the order should no longer matter.

```html
<highcharts-chart 
     [Highcharts]="Highcharts"
     [callbackFunction]="chartCallback"
     [options]="chartOptions"
     style="width: 100%; height: 400px; display: block;"
></highcharts-chart>
```

After applying these two corrections, your chart should work correctly.

**Comment by mateuszkornecki** [comment] 2020-06-25 11:16
Closing as a duplicate of #149.

**Closed by mateuszkornecki** 2020-06-25 11:16 UTC
Labels: Pending reply
