### ISSUE TITLE
Tree shaking removes imported module when in an external library

### ISSUE THREAD

**Issue by fil-forti** [highcharts/highcharts-angular#138] opened 2019-05-01 00:46 UTC
I have a highcharts component in an external library which is implemented following the example provided in this repository:

**tile-map-component.ts inside of library**
```
import * as Highcharts from 'highcharts';
import HeatMapModule from 'highcharts/modules/heatmap';
import TileMapModule from 'highcharts/modules/tilemap';
HeatMapModule(Highcharts);
TileMapModule(Highcharts);

@Component({
  selector: 'tile-map',
  templateUrl: './tile-map.component.html',
  styleUrls: ['./tile-map.component.scss']
})
export class TileMapComponent {
  @Input() data: MySeries;

  Highcharts: typeof Highcharts = Highcharts;
  options: Highcharts.Options;
 
  ...
}
```

**container-component.html inside of app**
```
...
<tile-map [data]="inputData"></tile-map>
...
```

The component is working when built with `ng serve` but it breaks when I build the app for production (`--prod`). I suspect is caused by the tree shaking because when I set the parameter `"buildOptimizer": false,` it works just fine. Is this a bug or am I doing something wrong?

Thank you

**Setup used**
    "@angular/common": "~7.1.0",
    "highcharts": "^7.1.1",
    "highcharts-angular": "^2.4.0",

**Comment by KacperMadej** [comment] 2019-05-07 08:14
Hi @fil-forti 

Thank you for reporting about the problem.

Please let me know more about the failed build - what's the error? when does it fail?

Could you check if you have the same error for a simple (e.g. line or column) chart type and without any additional modules loaded?

**Comment by patrickoneill46** [comment] 2019-05-16 06:21
Hi @fil-forti 

I had the exact same problem with the annotations module when creating a tree shaken build.

What I did was move the module part inside the constructor function

`constructor() {
   HeatMapModule(this.Highcharts);
   TileMapModule(this.Highcharts); 
}`

I'm looking into using a static function that resolves highcharts module imports in the angular module class as I think that may be a little cleaner. Hope the above works for you for now.

**Comment by fil-forti** [comment] 2019-05-29 20:19
Sorry for the very late reply, I had to work on another part of the project and didn't have time to test this.

@KacperMadej the error I was getting was 
`ERROR Error: Highcharts error #17: www.highcharts.com/errors/17`
so it seems it wasn't recognizing the series type 'tilemap'

@patrickoneill46 I moved the 2 modules inside the constructor and it worked! thanks a lot!

**Comment by KacperMadej** [comment] 2019-05-30 09:08
@fil-forti 
Please make sure that you have loaded and initialized required module for that series type.
You could always check with pure JS demos to see what modules are required or with documentation for each series. https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/honeycomb-usa/

https://code.highcharts.com/modules/tilemap.js

**Comment by fil-forti** [comment] 2019-05-31 22:32
@KacperMadej yeah, I was loading the right modules but they were removed during the tree shaking, the solution suggested by @patrickoneill46 actually solved the issue

**Comment by KacperMadej** [comment] 2019-06-03 10:19
@fil-forti 
Since the issue is solved I'll close it, but in case this is wrong please reopen.

**Closed by KacperMadej** 2019-06-03 10:19 UTC
Labels: Pending reply
