### ISSUE TITLE
When the series updates, the chart type updates, but the x axis labels remain the same. They don't update to reflect the new labels being sent in by the series.

### ISSUE THREAD

**Issue by scrayWC** [highcharts/highcharts-angular#238] opened 2020-11-05 21:54 UTC
I am using Angular 9 with highcharts-angular.  I have a chart that will update data based on the number of days a user has chosen.  It updates from a bar chart to an area chart depending on the amount of days. For data less than 14 days old, the bar chart shows and the dates which are the labels on the x-axis shows each day. For data greater than 14 days, the area chart shows with the x-axis showing every other day, or every 5 days, or however highcharts handles that.  I am only formatting the labels on the x-axis when days are below 14 days and the user is suppose to see a bar chart. The problem that I am running into is that the x-axis labels aren't updating when the series data is updating to reflect the update in the amount of days and the chart type. Because I am using Angular, I am not grabbing an instance of the chart options and updating it. I am passing into my template the [(update)]="boolean" and setting that to true in my component class when a user hits the button after updating the dates they want to view. I am using a service where I am using a ternary statement to update my chart. I have 2 functions, one for bar chart, the other for line chart, and when the amount of days in over 14 days, I return the lineChartOptions. This is all part of the observable I am returning to my component class where i subscribe and set my variables on the class to be put into the template. 

Thanks so much for your help in this.

**Comment by mateuszkornecki** [comment] 2020-11-06 06:50
Hello, @scrayWC 

Thanks for reporting the issue.

It is hard to tell you what is not working without taking look at your code. Could you reproduce the issue in an online editor that we can work on? It will be much easier to find a source of the problem while having access to the problem itself. You can start from this template: https://stackblitz.com/edit/highcharts-angular-basic-line

Also keep in mind that for the general tech support you can contact us through one of the support channels (forum, email, skype), please see www.highcharts.com/support.

**Comment by scrayWC** [comment] 2020-11-06 15:14
Hello @mateuszkornecki , here is the updated issue. I am having issues with stackblitz as I attempt to add in a button to update the numOfDays variable above 14 so that the chart would change from column type to area type. But I have in there most of all what I am attempting to do, which is to update the chart from Column type to Area type as the number of days increase pass 14. Under 14 days, show the column type and over 14 show area type. The issue I am having has to do with the update to the chart not showing in the view if a user attempts to enter over 14 days after the loading of the page. https://stackblitz.com/edit/highcharts-angular-basic-line-8jq6ga?file=src/app/app.component.ts

**Comment by mateuszkornecki** [comment] 2020-11-09 08:46
I prepared a simple demo for you, you can find there an example of updating the chart type on a click.

**Live demo:** 
https://stackblitz.com/edit/highcharts-angular-optimal-way-to-update-winbri

**Comment by scrayWC** [comment] 2020-11-09 13:42
@mateuszkornecki Hello there. The demo I created on Friday is finally working correctly. Here is the live demo of the issue I am having: https://stackblitz.com/edit/highcharts-angular-basic-line-8jq6ga?file=src%2Fapp%2Fapp.component.ts

Check out this video link of what i am attempting to do here: https://drive.google.com/file/d/1ACHYrkRgC13gYPMk0Y3XuJQasJzmGd3g/view

**Comment by scrayWC** [comment] 2020-11-09 13:53
Hopefully the updated demo with the clickme button : https://stackblitz.com/edit/highcharts-angular-basic-line-8jq6ga?file=src/app/app.component.ts

**Comment by mateuszkornecki** [comment] 2020-11-09 14:19
Sorry, it seems that I misunderstood you.

It is happening because you are specifying the `tickPositions` only for the bar chart. While updating by default Highcharts is updating just the changed properties - because of that your area chart is still using tickPositions set by the bar one. To fix that you could simply delete `tickPositions` from the bar chart config, or set the new one for area one.

**Live demo:**
https://stackblitz.com/edit/highcharts-angular-basic-line-7ifv9r?file=src%2Fapp%2Fdata.service.ts

**Comment by scrayWC** [comment] 2020-11-09 15:51
@mateuszkornecki Thanks so much for taking a look at this for me.  There is just one thing that I don't quite understand. In the documentation, it states that by default, the tickPositions is set to undefined.  So when I  set the tickPositions property to undefined in the areaChart options, and update to the bar chart and back it still doesn't update properly. Why is that happening?

**Comment by scrayWC** [comment] 2020-11-09 16:22
@mateuszkornecki I tried your second solution, where I am setting my tickPositions in the area chart, and it still is showing up as undefined. Here is the demo code here :https://stackblitz.com/edit/highcharts-angular-basic-line-7ifv9r?file=src/app/data.service.ts

**Comment by mateuszkornecki** [comment] 2020-11-10 08:49
It seems that you send me a not forked demo - I can't see any changes there. Anyway, you can try another approach, if you want to set tickPositions just for one "options set" and then set the default positions for another one you could just set them to `null`.

**Simplied demo:** 
https://stackblitz.com/edit/highcharts-angular-optimal-way-to-update-jourzq?file=src%2Fapp%2Fapp.component.ts

**Comment by scrayWC** [comment] 2020-11-10 15:03
@mateuszkornecki Thanks so much for this solution. Setting it to null seems to work well. Here is the updated demo : https://stackblitz.com/edit/highcharts-angular-basic-line-8jq6ga?file=src/app/data.service.ts

**Comment by mateuszkornecki** [comment] 2020-11-11 07:17
You're welcome! I am glad to hear it. 😄 

Closing since the problem seems to be resolved.

**Closed by mateuszkornecki** 2020-11-11 07:17 UTC
Labels: Pending reply
