### ISSUE TITLE
Add a live demo for how to use proj4.js in case of Highmaps charts/maps.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-angular#160] opened 2019-08-27 08:54 UTC
### Requested feature description
Add a live demo for how to use proj4.js in case of Highmaps charts/maps.

**Comment by KacperMadej** [comment] 2019-08-27 12:21
Here it is: https://codesandbox.io/s/angular-0b1w7

It should go to FAQ section as soon as it will be a frequently asked.

**Comment by ashnewport** [comment] 2020-01-20 13:28
@KacperMadej how does that example work in codesandbox but not when downloaded for offline/local development or copied to stackblitz? 😕

I am trying to integrate a [Highmaps demo for flight paths](https://www.highcharts.com/maps/demo/flight-routes) but the documentation is lacking and the codesandbox example isn't usable. E.g. in `app.component.ts` line 21 reports `Property 'win' does not exist on type 'typeof import("c:/dev/angular/node_modules/highcharts/highcharts.src")'.ts(2339)`

Following the `highcharts-angular` readme/docs results in an error `TypeError: Cannot read property 'features' of undefined` which is probably because of missing code like needing to include `proj4`; additionally after seeing the codesandbox it is unclear to use either `import * as Highcharts from "highcharts/highcharts.src";` or `import * as Highcharts from 'highcharts';`.

Is the demo of using `proj4.js` still accurate and up to date? If not, what versions are compatible to get a working solution?

**Comment by KacperMadej** [comment] 2020-01-21 10:10
Hi @ashnewport 

Download from codesandbox doesn't work for me either, but this is the sandbox issue. Please try using the code in your or a new Angular app. I have tested this locally on the app from this repo and it was working fine. In case of problems with this please leave another comment and in case you would like to get more help regarding Highcharts please contact our technical support - https://www.highcharts.com/blog/support/

**Comment by ashnewport** [comment] 2020-01-22 00:19
@KacperMadej still not working with `proj4` as expected.

Steps to replicate:

1. Clone repository, install and [run the demo](https://github.com/highcharts/highcharts-angular#demo-app) - this works successfully
2. `npm i proj4 --save`
3. Copy `app.module.ts`, `app.component.ts`, and `app.component.html` code from the [codesandbox demo](https://codesandbox.io/s/angular-0b1w7)
4. `npm run start` will throw a few compilation errors and fail to compile.
    - `ERROR in src/app/app.component.ts(18,11): error TS2345: Argument of type 'typeof import("C:/Users/Dev/Documents/highcharts-angular/node_modules/highcharts/highcharts.src")' is not assignable to parameter of type 'typeof import("C:/Users/Dev/Documents/highcharts-angular/node_modules/highcharts/highcharts")'.`
    - `Property 'geojson' is missing in type 'typeof import("C:/Users/Dev/Documents/highcharts-angular/node_modules/highcharts/highcharts.src")'.`
    - `src/app/app.component.ts(21,13): error TS2339: Property 'win' does not exist on type 'typeof import("C:/Users/Dev/Documents/highcharts-angular/node_modules/highcharts/highcharts.src")'.`
![image](https://user-images.githubusercontent.com/3241448/72850942-66117000-3cfe-11ea-9689-1dd45e26bfc2.png)
5. Save any file again and it will compile successfully. E.g. open `app.component.ts` and press `Ctrl+S` to save and trigger a compilation. The errors will still be logged in the terminal but this time it compiles successfully.
6. Go to http://localhost:4200/ and the map no longer loads; errors are logged to the console relating to `proj4` and http://www.highcharts.com/errors/22
![image](https://user-images.githubusercontent.com/3241448/72851352-83930980-3cff-11ea-989c-6fef5c209578.png)

To make the above replication easier, I've forked the demo, made my changes and published to https://github.com/ashnewport/highcharts-angular. You can clone that if you'd like and execute `npm start` to save some time and a few steps from above.

Some additional tweaks which I have _not_ committed to my fork:
I can get rid of the compilation errors with a few castings which doesn't feel super great but inside `app.component.ts` update to:
```typescript
// init map module
MapModule(Highcharts as any);

// add proj4 to window, so Highcharts will be able to find it
(Highcharts as any).win = (Highcharts as any).win || {};
(Highcharts as any).win.proj4 = proj4;
```
Just for extra measure `npm install highcharts-angular --save` so we can visually see it in the `package.json` as `"highcharts-angular": "file:highcharts-angular"` when using the demo app.

I encounter the same issues when installing with the latest Angular, Highcharts and proj4 libraries so I don't know if this is a version compatibility issue or just some missing interfaces.

Lastly, if you feel this is getting off topic from the GitHub Issue then I'm happy to move over to the forms for further support.

**Comment by KacperMadej** [comment] 2020-01-22 11:41
Thank you for the demo and the details of the problem. We will be investigating the problem and preparing an updated demo for the case soon. For now, I can say that some TS issues/warnings could be simply prevented by `any` casting.

Additionally:
The need to set the proj4 on Window is caused by Highcharts, so when this will be resolved the code in Angular should be cleaner.
This enhancement depends on the Highcharts feature in here: https://github.com/highcharts/highcharts/issues/12829

**Comment by KacperMadej** [comment] 2020-01-24 16:55
@ashnewport 
Please check the current master branch as it was recently updated with a demo sample for the proj4.
Related PR with commits: https://github.com/highcharts/highcharts-angular/pull/173

**Comment by ashnewport** [comment] 2020-01-29 01:34
@KacperMadej 
Awesome it works as expected now! I've tested and confirmed in my own code.

FWIW prior to your updates, inside my project I did the following which got the maps with lat/lng to work:
```typescript
import * as Highcharts from 'highcharts';
import proj4 from 'proj4';
MapModule(Highcharts as any);
// @ts-ignore: Unreachable code error
(Highcharts.win as any).proj4 = proj4;
```
Pretty ugly but it worked and might be of use to someone else who gets stuck and for whatever reason is unable to update packages.

**Comment by mateuszkornecki** [comment] 2020-08-31 07:15
It is worth mentioning that since the Highcharts 8.0.1 version it is possible to load the proj4 library through the chart options (`chart.proj4`). Thanks to that feature the library might be used without being available in the window context.

**API references:**
https://api.highcharts.com/highmaps/chart.proj4

**Changelog:** 
https://www.highcharts.com/blog/changelog/#highcharts-maps-v8.0.1

**Comment by mueedahmed1** [comment] 2020-09-02 10:48
@mateuszkornecki  can you please define how to use proj4 in highcharts-angular?

**Comment by mateuszkornecki** [comment] 2020-09-03 05:59
Sure, the working example is already added in the demo app that can be found in the `highcharts-angular` repository. All you need to do is to import the proj4 library, and then pass it to the `chart.proj4` property.

https://github.com/highcharts/highcharts-angular/blob/master/src/app/map-chart/map-chart.component.ts

**Comment by mueedahmed1** [comment] 2020-09-04 11:32
@mateuszkornecki Thanks, it works as expected!

**Comment by mueedahmed1** [comment] 2020-09-10 06:39
@mateuszkornecki Problem is when I am showing datapoints on map it is slowing down my page and when doing zoom in or zoom out on map it is also slowing down my page, I mean it make my page unresponsive. please guide me how to handle this issue. Datapoints are upto 10,000 or maybe 50,000. I am also using boost and turbo threshold  properties but still same behaviour.

**Comment by mateuszkornecki** [comment] 2020-09-10 07:04
@mueedahmed1 For general tech support, please contact us through one of the support channels:  www.highcharts.com/support.

**Closed** 2021-01-04 13:27 UTC
Labels: docs, enhancement
