### ISSUE TITLE
Local reference in the package.

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts-angular#229] opened 2020-09-18 06:41 UTC
### Describe the bug
It seems that there is a reference to local repository in the master code.

```“D:/a/1/s/src/reaper.spa/ClientApp/node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts.map” for “D:/a/1/s/src/reaper.spa/ClientApp/node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts”: Error: Internal Error: relativeFrom(C:/Users/Admin/Desktop/blacklabel/git_repos/highcharts-angular/dist/highcharts-angular/lib/highcharts-chart.component.d.ts): path is not relative```

### Expected behavior
There shouldn't be any local reference in the production code.

### Setup used
```
“dependencies”: {
   “@angular/animations”: “9.1.12”,
   “@angular/cdk”: “9.2.4”,
   “@angular/common”: “9.1.12”,
   “@angular/compiler”: “9.1.12”,
   “@angular/core”: “9.1.12”,
   “@angular/forms”: “9.1.12”,
   “@angular/material”: “^9.2.4”,
   “@angular/platform-browser”: “9.1.12”,
   “@angular/platform-browser-dynamic”: “9.1.12”,
   “@angular/platform-server”: “9.1.12”,
   “@angular/router”: “9.1.12”,
   “@azure/msal-angular”: “^1.0.0”,
   “@fortawesome/angular-fontawesome”: “^0.6.0”,
   “@fortawesome/fontawesome-svg-core”: “^1.2.30”,
   “@fortawesome/free-solid-svg-icons”: “^5.14.0”,
   “aspnet-prerendering”: “^3.0.1”,
   “bootstrap”: “^4.5.2”,
   “core-js”: “^3.6.5”,
   “guid-typescript”: “1.0.9”,
   “hammerjs”: “^2.0.8”,
   “highcharts”: “8.1.2”,
   “highcharts-angular”: “2.7.0”,
   “jquery”: “^3.5.1”,
   “moment”: “^2.27.0”,
   “msal”: “^1.3.4”,
   “ngx-drag-scroll”: “^9.0.0-beta.3”,
   “ngx-moveable”: “^0.14.3”,
   “oidc-client”: “^1.9.1”,
   “popper.js”: “^1.16.0”,
   “primeicons”: “4.0.0”,
   “primeng”: “10.0.0-rc.1”,
   “rxjs”: “^6.6.2”,
   “rxjs-compat”: “6.5.5”,
   “tslib”: “^1.13.0”,
   “zone.js”: “~0.10.2”
 },
```

**Comment by mateuszkornecki** [comment] 2020-09-18 07:04
_Internal note:_

There is a chance that the problem only affects the 2.7.0 version and below since the newest wrapper was build on the mac not windows.

**Comment by lcapka** [comment] 2020-10-09 10:55
Hello,
I up vote for this issue. We see the same problem. In our case the issue is "visible" only when the drive where the build runs is different from C: (in our case it's R:). In the described case it's D:. Hope it helps.

**Comment by lcapka** [comment] 2020-10-10 08:34
And one more idea - it start working well after upgrade to 2.8.0. The previous comment was related to 2.7.0 so it's been already fixed.

**Comment by karolkolodziej** [comment] 2020-10-12 08:08
Thank you for confirming our suspicions. 
Closing because the issue has been already fixed.

**Closed by karolkolodziej** 2020-10-12 08:08 UTC
Labels: Unable to recreate
