### ISSUE TITLE
Stacked column chart not rendering on modifying the chart options

### ISSUE THREAD

**Issue by saravana-sk** [highcharts/highcharts-angular#258] opened 2021-01-07 10:14 UTC
We have migrated HighCharts from 7.2.1 to 8.2.2. From then, the stacked column charts are not rendering properly. The configuration for stacking is set to "normal" on chart options. Still its not working. 

After updating highcharts-angular from 2.4.0 to 2.9.0, the initial rendering starts working fine. But if I update the chart options programatically, the stack issue fails again. 

### Expected behavior
The column stacking should render properly, as well as the StackLabels.

### Demo
https://stackblitz.com/edit/angular-ivy-a5kdrb

#### Steps required to recreate the problem in the demo:
1. Verify the chart rendering on initial load. Like stacking and stack labels.
2. Now, click Update Options button and check the stacking behaviour

### Setup used
 - NodeJS version : v12.19.0
 - Angular version : 7.2.15
 - TypeScript version : 3.2.2

**Comment by mateuszkornecki** [comment] 2021-01-07 13:00
Hey @saravana-sk, thanks for reporting the issue.

It looks like a highcharts regression bug for me - not related to the highcharts-angular wrapper itself. I noticed that everything was working correctly in the highcharts. 8.1.0 version. I already reported the issue on the highcharts repository, you can track the progress here: https://github.com/highcharts/highcharts/issues/14890

**Comment by mateuszkornecki** [comment] 2021-01-07 13:01
Closing as the issue is not related to the `highcharts-angular` wrapper.

**Closed by mateuszkornecki** 2021-01-07 13:01 UTC

**Comment by saravana-sk** [comment] 2021-01-07 13:17
Thanks @mateuszkornecki. I will track in the highcharts repo.
